sudo: required
language: python
python:
  - "3.8"
addons:
  chrome: stable
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python3 -c "import nltk; nltk.download('punkt'); nltk.download('maxent_ne_chunker'); nltk.download('words');nltk.download('averaged_perceptron_tagger');"
# command to run tests
script:
    - python3 -m pytest
