# -*- coding: utf-8 -*-
"""Mockup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lucJiMQUyLmduJ8yu98m3OqoVbukAzSU
"""
import flask
import ngrok as ngrok

!pip install flask-ngrok

# Commented out IPython magic to ensure Python compatibility.
# %mkdir templates -p

# Commented out IPython magic to ensure Python compatibility.
# %%writefile templates/base.html
# <!doctype html>
# <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
# <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
# <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
# <title>Personality Match - {% block title %}{% endblock %}</title>
# <nav class="navbar navbar-inverse">
# <div class="navbar-header">
#   <a class="navbar-brand" href="{{ url_for('home') }}">Personality Match</a>
#   </div>
# </nav>
# <section class="content">
#   <header>
#     {% block header %}{% endblock %}
#   </header>
#   {% block content %}{% endblock %}
# </section>

# Commented out IPython magic to ensure Python compatibility.
# %%writefile templates/index.html
# {% extends 'base.html' %}
# {% block header %}
#   <h1>{% block title %}Mockup Home{% endblock %}</h1>
# {% endblock %}
# 
# {% block content %}
#   <form method="post">
#     <label for="name">Name</label>
#     <input name="name" id="name" required>
#     <br>
#     <label for="usertext">Enter Your Speech:</label>
#     <input style="width:400px;" name="usertext" id="usertext" required>
#     <br>
#     <input type="radio" id="similar" name="testType" value="similar" checked>
#     <label for="similar">Most Similar To</label><br>
#     <input type="radio" id="different" name="testType" value="different">
#     <label for="">Most Different From</label><br>
#     <input type="radio" id="friend" name="testType" value="friend">
#     <label for="friend">Most Likely to Become Friends With</label>
#     <br>
#     <input type="submit" value="Submit">
#   </form>
# {% endblock %}
# 
# </html>

# Commented out IPython magic to ensure Python compatibility.
# %%writefile templates/output.html
# {% extends 'base.html' %}
# {% block header %}
#   <h1>{% block title %}Mockup Output{% endblock %}</h1>
# {% endblock %}
# 
# {% block content %}
#   <div>
#     <P>You, Bob, have been matched with ....</p>
#     <h1>Sherlock Holmes!!!!!</h1>
#     <img src="https://upload.wikimedia.org/wikipedia/commons/c/cd/Sherlock_Holmes_Portrait_Paget.jpg" alt="Sherlock">
#   </div>
#   <div>
#     <P>Here are some quotes from this character:</p>
#     <ul>
#       <li>“When you have eliminated the impossible, whatever remains, however improbable, must be the truth?” — The Sign of Four</li>
#       <li>“Watson. Come at once if convenient. If inconvenient, come all the same.” — The Adventure of the Creeping Man</li>
#       <li>“I am a brain, Watson. The rest of me is a mere appendix.” ― The Adventure of the Mazarin Stone </li>
#     </ul>
#   </div>
#   <div>
#   <p>You were matched with this character because you are:</p>
#   <ul>
#     <li>Bossy</li>
#     <li>Perceptive</li>
#     <li>Stubborn</li>
#   </ul>
#   </div>
#   <div>
#   <p>Top characters other users matched with:</p>
#   <ol>
#     <li>Sherlock Holmes</li>
#     <li>Jane Eyre</li>
#     <li>Marius Pontmercy</li>
#   </ol>
#   </div>
# {% endblock %}
# 
# </html>

from flask_ngrok import run_with_ngrok
from flask import Flask
from flask import render_template
from flask import (
    redirect, request, url_for
)

app = Flask(__name__)
run_with_ngrok(app)   #starts ngrok when the app is run
@app.route("/", methods=('GET','POST'))
def home(name=None):
    if request.method == 'POST':
      return redirect(url_for('submit'))  
    return render_template('index.html', name=name)

@app.route("/submit")
def submit(name=None):
  return render_template('output.html', name=name)


app.run()